# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc1906bbe7d2e75087950f2032d7d592eeea014aee0dfcf8a74fcbab04ad778df5087eb6f9b65b385dbc301c3b46ca07bb4d6043b7bd85629a4e4ebf0419f0c0

test:
  secret_key_base: bad7d5a3724b40b8d1a385386e504582f63c9f23bb950dee99e6297e73e4a4624ac8866d0829232e2ae5ee72e0de5363a9d5f16d41d169116dbc5261ef75558e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
