source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'sass-rails', '~> 5.0.3'
gem 'uglifier', '>= 2.7.1'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem "haml-rails", "~> 1.0"
gem 'ruby_gg', '~> 0.1.4.5'
gem 'redis-rails', '~> 5.0', '>= 5.0.2'
gem "omniauth-google-oauth2", "~> 0.2.1"

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
  gem 'database_cleaner'                        # to clear Cucumber's test database between runs
  gem 'capybara', '2.7.1'          # lets Cucumber pretend to be a web browser
  gem 'launchy'                                 # a useful debugging aid for user stories
  gem 'rspec-rails'
  gem 'cucumber', '2.4.0'
end

gem 'bcrypt-ruby', :require => 'bcrypt'

group :test do
  gem 'cucumber-rails', '1.4.3'
  gem 'cucumber-rails-training-wheels'
end